-- Baseline: refleja el esquema real de la base de datos AdrithStore tal como
-- existia antes de introducir Flyway (generado por Hibernate ddl-auto=update
-- a lo largo del desarrollo). Este script NO se ejecuta contra la base de
-- datos de produccion real -- ahi Flyway la marca como "baseline" via
-- flyway.baseline-on-migrate=true (ver application.properties), asumiendo que
-- el esquema ya esta en este estado. Este archivo sirve para:
--   1) documentar/versionar el esquema como punto de partida de Flyway,
--   2) permitir levantar una base de datos nueva desde cero (ej. otra
--      maquina de desarrollo) sin depender de Hibernate ddl-auto.
-- Extraido con: pg_dump --schema-only --no-owner --no-privileges

CREATE TABLE public.categorias (
    id_categoria integer NOT NULL,
    descripcion character varying(255),
    nombre character varying(255) NOT NULL
);

ALTER TABLE public.categorias ALTER COLUMN id_categoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorias_id_categoria_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.cierre_diario (
    id_cierre integer NOT NULL,
    ajuste_registrado boolean,
    cerrado_en timestamp(6) without time zone,
    cerrado_por character varying(50),
    diferencia numeric(12,2) NOT NULL,
    estado character varying(20),
    fecha_cierre date NOT NULL,
    fondo_dejado numeric(12,2) NOT NULL,
    observacion character varying(255),
    retiro numeric(12,2) NOT NULL,
    saldo_contado numeric(12,2) NOT NULL,
    saldo_sistema numeric(12,2) NOT NULL,
    id_cuenta integer NOT NULL
);

ALTER TABLE public.cierre_diario ALTER COLUMN id_cierre ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cierre_diario_id_cierre_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.cliente (
    id_cliente integer NOT NULL,
    apellido character varying(255),
    dni character varying(255),
    nombre character varying(255),
    telefono character varying(255)
);

ALTER TABLE public.cliente ALTER COLUMN id_cliente ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cliente_id_cliente_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.compra (
    descuento_global numeric(10,2),
    id_compra integer NOT NULL,
    id_proveedor integer,
    percepcion numeric(10,2),
    subtotal numeric(10,2),
    total numeric(10,2),
    fecha timestamp(6) without time zone,
    estado character varying(255),
    motivo character varying(255),
    serie_comprobante character varying(255),
    tipo_comprobante character varying(255),
    medio_pago character varying(255)
);

CREATE TABLE public.compra_ajuste (
    costo_anterior numeric(10,4),
    costo_nuevo numeric(10,4),
    cpp_resultante numeric(10,4),
    delta_cantidad numeric(10,3),
    id_ajuste integer NOT NULL,
    id_compra_original integer,
    id_producto integer,
    impacto_stock numeric(10,3),
    fecha timestamp(6) without time zone,
    motivo character varying(255) NOT NULL,
    tipo character varying(255) NOT NULL
);

ALTER TABLE public.compra_ajuste ALTER COLUMN id_ajuste ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compra_ajuste_id_ajuste_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.compra_detalle (
    cantidad numeric(10,3),
    costo_anterior numeric(10,4),
    costo_unitario numeric(10,4),
    descuento_pct numeric(5,2),
    id_compra integer,
    id_compra_detalle integer NOT NULL,
    id_producto integer,
    id_unidad integer,
    subtotal numeric(10,2),
    vencimiento date
);

ALTER TABLE public.compra_detalle ALTER COLUMN id_compra_detalle ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compra_detalle_id_compra_detalle_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE public.compra ALTER COLUMN id_compra ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compra_id_compra_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.cuenta_financiera (
    activa boolean,
    id_cuenta integer NOT NULL,
    saldo_actual numeric(12,2),
    tipo character varying(20),
    descripcion character varying(255),
    nombre character varying(255) NOT NULL,
    fondo_caja numeric(12,2)
);

ALTER TABLE public.cuenta_financiera ALTER COLUMN id_cuenta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuenta_financiera_id_cuenta_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.evento_log (
    id_entidad integer,
    id_evento integer NOT NULL,
    fecha timestamp(6) without time zone,
    entidad character varying(30),
    tipo_evento character varying(60) NOT NULL,
    datos_json text,
    descripcion text
);

ALTER TABLE public.evento_log ALTER COLUMN id_evento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evento_log_id_evento_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.periodo_contable (
    id_periodo integer NOT NULL,
    periodo character varying(7),
    fecha_apertura timestamp(6) without time zone,
    estado character varying(20),
    notas character varying(255)
);

ALTER TABLE public.periodo_contable ALTER COLUMN id_periodo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.periodo_contable_id_periodo_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.producto (
    comision_base numeric(10,2),
    comision_cada numeric(10,2),
    cpp numeric(10,4),
    id_categoria integer,
    id_producto integer NOT NULL,
    permite_stock_negativo boolean,
    precio_costo numeric(10,4),
    precio_venta numeric(10,2),
    stock numeric(10,3),
    stock_alert numeric(10,3),
    visible_en_pos boolean,
    tipo character varying(20),
    descripcion character varying(255),
    imagen_url character varying(255),
    nombre character varying(255) NOT NULL,
    sku character varying(255),
    porcentaje_costo numeric(5,2),
    unidad_medida character varying(10) DEFAULT 'UNIDAD'::character varying NOT NULL,
    CONSTRAINT producto_unidad_medida_check CHECK (((unidad_medida)::text = ANY ((ARRAY['UNIDAD'::character varying, 'KG'::character varying])::text[])))
);

ALTER TABLE public.producto ALTER COLUMN id_producto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_id_producto_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.producto_unidad (
    id_producto integer NOT NULL,
    id_unidad integer NOT NULL,
    precio_venta numeric(10,2),
    unidad integer NOT NULL,
    medida character varying(255),
    nombre_unidad character varying(255) NOT NULL
);

ALTER TABLE public.producto_unidad ALTER COLUMN id_unidad ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_unidad_id_unidad_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.proveedores (
    emite_percepcion boolean,
    id_proveedor integer NOT NULL,
    contacto character varying(255),
    descripcion character varying(255),
    email character varying(255),
    empresa character varying(255) NOT NULL,
    ruc character varying(255),
    telefono character varying(255)
);

ALTER TABLE public.proveedores ALTER COLUMN id_proveedor ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proveedores_id_proveedor_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.sistema_config (
    configurado boolean,
    id integer NOT NULL,
    fecha_setup timestamp(6) without time zone,
    nombre_negocio character varying(200)
);

CREATE TABLE public.transaccion_financiera (
    id_compra integer,
    id_cuenta integer,
    id_transaccion integer NOT NULL,
    id_venta integer,
    monto numeric(10,2),
    signo integer,
    periodo character varying(7),
    fecha timestamp(6) without time zone,
    tipo_mov character varying(30),
    creada_por character varying(50),
    concepto character varying(255),
    CONSTRAINT ck_transaccion_tipo_mov CHECK (((tipo_mov)::text = ANY ((ARRAY['APERTURA'::character varying, 'VENTA'::character varying, 'COMPRA'::character varying, 'GASTO'::character varying, 'CAMBIO_DIGITAL'::character varying, 'AJUSTE'::character varying, 'TRANSFERENCIA'::character varying, 'RETIRO'::character varying])::text[])))
);

ALTER TABLE public.transaccion_financiera ALTER COLUMN id_transaccion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaccion_financiera_id_transaccion_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.usuario (
    activo boolean,
    id_usuario integer NOT NULL,
    fecha_creacion timestamp(6) without time zone,
    dni character varying(15),
    rol character varying(20) NOT NULL,
    telefono character varying(20),
    creado_por character varying(50),
    username character varying(50) NOT NULL,
    apellidos character varying(100) NOT NULL,
    nombres character varying(100) NOT NULL,
    password_hash character varying(255) NOT NULL
);

ALTER TABLE public.usuario ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_usuario_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.venta (
    id_cliente integer NOT NULL,
    id_venta integer NOT NULL,
    igv numeric(10,2),
    serie_comprobante character varying(255),
    subtotal numeric(10,2),
    total numeric(10,2),
    fecha timestamp(6) without time zone,
    estado character varying(255),
    tipo_comprobante character varying(255),
    motivo character varying(255),
    medio_pago character varying(255),
    id_usuario integer,
    descuento_global numeric(10,2) DEFAULT 0
);

CREATE TABLE public.venta_detalle (
    cantidad numeric(10,3) NOT NULL,
    comision_cobrada numeric(10,2),
    costo_historico numeric(10,4) NOT NULL,
    descuento_aplicado numeric(10,2),
    id_producto integer NOT NULL,
    id_unidad integer,
    id_venta integer NOT NULL,
    id_venta_detalle integer NOT NULL,
    monto_operacion numeric(10,2),
    pct_descuento numeric(5,2),
    precio_historico numeric(10,2) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    descuento_item numeric(10,2) DEFAULT 0
);

ALTER TABLE public.venta_detalle ALTER COLUMN id_venta_detalle ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.venta_detalle_id_venta_detalle_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.venta_detalle_servicio (
    id_venta_detalle_servicio integer NOT NULL,
    comision numeric(10,2),
    costo numeric(10,4),
    descripcion character varying(255),
    destino character varying(255),
    monto numeric(10,2),
    origen character varying(255),
    subtotal numeric(10,2),
    id_producto integer,
    id_venta integer
);

ALTER TABLE public.venta_detalle_servicio ALTER COLUMN id_venta_detalle_servicio ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.venta_detalle_servicio_id_venta_detalle_servicio_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE public.venta ALTER COLUMN id_venta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.venta_id_venta_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.venta_pago (
    id_pago integer NOT NULL,
    id_venta integer NOT NULL,
    monto numeric(10,2) NOT NULL,
    medio_pago character varying(50) NOT NULL
);

ALTER TABLE public.venta_pago ALTER COLUMN id_pago ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.venta_pago_id_pago_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- Primary keys / unique constraints

ALTER TABLE ONLY public.categorias ADD CONSTRAINT categorias_nombre_key UNIQUE (nombre);
ALTER TABLE ONLY public.categorias ADD CONSTRAINT categorias_pkey PRIMARY KEY (id_categoria);
ALTER TABLE ONLY public.cierre_diario ADD CONSTRAINT cierre_diario_pkey PRIMARY KEY (id_cierre);
ALTER TABLE ONLY public.cliente ADD CONSTRAINT cliente_pkey PRIMARY KEY (id_cliente);
ALTER TABLE ONLY public.compra_ajuste ADD CONSTRAINT compra_ajuste_pkey PRIMARY KEY (id_ajuste);
ALTER TABLE ONLY public.compra_detalle ADD CONSTRAINT compra_detalle_pkey PRIMARY KEY (id_compra_detalle);
ALTER TABLE ONLY public.compra ADD CONSTRAINT compra_pkey PRIMARY KEY (id_compra);
ALTER TABLE ONLY public.cuenta_financiera ADD CONSTRAINT cuenta_financiera_pkey PRIMARY KEY (id_cuenta);
ALTER TABLE ONLY public.evento_log ADD CONSTRAINT evento_log_pkey PRIMARY KEY (id_evento);
ALTER TABLE ONLY public.periodo_contable ADD CONSTRAINT periodo_contable_periodo_key UNIQUE (periodo);
ALTER TABLE ONLY public.periodo_contable ADD CONSTRAINT periodo_contable_pkey PRIMARY KEY (id_periodo);
ALTER TABLE ONLY public.producto ADD CONSTRAINT producto_pkey PRIMARY KEY (id_producto);
ALTER TABLE ONLY public.producto ADD CONSTRAINT producto_sku_key UNIQUE (sku);
ALTER TABLE ONLY public.producto_unidad ADD CONSTRAINT producto_unidad_id_producto_nombre_unidad_key UNIQUE (id_producto, nombre_unidad);
ALTER TABLE ONLY public.producto_unidad ADD CONSTRAINT producto_unidad_pkey PRIMARY KEY (id_unidad);
ALTER TABLE ONLY public.proveedores ADD CONSTRAINT proveedores_empresa_key UNIQUE (empresa);
ALTER TABLE ONLY public.proveedores ADD CONSTRAINT proveedores_pkey PRIMARY KEY (id_proveedor);
ALTER TABLE ONLY public.proveedores ADD CONSTRAINT proveedores_ruc_key UNIQUE (ruc);
ALTER TABLE ONLY public.sistema_config ADD CONSTRAINT sistema_config_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.transaccion_financiera ADD CONSTRAINT transaccion_financiera_pkey PRIMARY KEY (id_transaccion);
ALTER TABLE ONLY public.usuario ADD CONSTRAINT usuario_dni_key UNIQUE (dni);
ALTER TABLE ONLY public.usuario ADD CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario);
ALTER TABLE ONLY public.usuario ADD CONSTRAINT usuario_username_key UNIQUE (username);
ALTER TABLE ONLY public.venta_detalle ADD CONSTRAINT venta_detalle_pkey PRIMARY KEY (id_venta_detalle);
ALTER TABLE ONLY public.venta_detalle_servicio ADD CONSTRAINT venta_detalle_servicio_pkey PRIMARY KEY (id_venta_detalle_servicio);
ALTER TABLE ONLY public.venta_pago ADD CONSTRAINT venta_pago_pkey PRIMARY KEY (id_pago);
ALTER TABLE ONLY public.venta ADD CONSTRAINT venta_pkey PRIMARY KEY (id_venta);

-- Foreign keys

ALTER TABLE ONLY public.producto_unidad ADD CONSTRAINT fk366ga2qbvysdjncbjf2cx90bf FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto);
ALTER TABLE ONLY public.venta_detalle ADD CONSTRAINT fk6khmcv084256h2i55922prpxl FOREIGN KEY (id_unidad) REFERENCES public.producto_unidad(id_unidad);
ALTER TABLE ONLY public.producto ADD CONSTRAINT fk7ecb6ylnupmgh6om5mbtqrpm4 FOREIGN KEY (id_categoria) REFERENCES public.categorias(id_categoria);
ALTER TABLE ONLY public.transaccion_financiera ADD CONSTRAINT fk8wddofy638lov3uhehodhhria FOREIGN KEY (id_cuenta) REFERENCES public.cuenta_financiera(id_cuenta);
ALTER TABLE ONLY public.compra_ajuste ADD CONSTRAINT fk97kcljotkeau1n182nw35gin9 FOREIGN KEY (id_compra_original) REFERENCES public.compra(id_compra);
ALTER TABLE ONLY public.venta_detalle ADD CONSTRAINT fkclaa78twf7o52j8kvie9pt218 FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto);
ALTER TABLE ONLY public.compra_detalle ADD CONSTRAINT fkdslf39a4nlq9mqpd0kxwxwby9 FOREIGN KEY (id_unidad) REFERENCES public.producto_unidad(id_unidad);
ALTER TABLE ONLY public.venta_detalle_servicio ADD CONSTRAINT fkfcagta18pecmfjd2bkho55q12 FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto);
ALTER TABLE ONLY public.compra_detalle ADD CONSTRAINT fkkgox3wo4pbnqpwkic8v82mkt FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto);
ALTER TABLE ONLY public.compra_ajuste ADD CONSTRAINT fkmoec6bdf7touig9s6f0qioj5u FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto);
ALTER TABLE ONLY public.venta ADD CONSTRAINT fkoilu1fdfgmu7sfe0spen005ms FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario);
ALTER TABLE ONLY public.venta_pago ADD CONSTRAINT fkovaut1l4cqv33a1fpr0o49lkl FOREIGN KEY (id_venta) REFERENCES public.venta(id_venta);
ALTER TABLE ONLY public.compra_detalle ADD CONSTRAINT fkq1r15atutieuwa9yy0vy1nm4r FOREIGN KEY (id_compra) REFERENCES public.compra(id_compra);
ALTER TABLE ONLY public.compra ADD CONSTRAINT fkqjcicg67km5rb8lhn7s54j11y FOREIGN KEY (id_proveedor) REFERENCES public.proveedores(id_proveedor);
ALTER TABLE ONLY public.venta_detalle ADD CONSTRAINT fkrhdv8ci51e1bwdcgrp9ls8ko4 FOREIGN KEY (id_venta) REFERENCES public.venta(id_venta);
ALTER TABLE ONLY public.cierre_diario ADD CONSTRAINT fkrk37vocl4uoifp99uca5bi9ya FOREIGN KEY (id_cuenta) REFERENCES public.cuenta_financiera(id_cuenta);
ALTER TABLE ONLY public.venta ADD CONSTRAINT fksor2qmi3thao7a8or49vlohp9 FOREIGN KEY (id_cliente) REFERENCES public.cliente(id_cliente);
ALTER TABLE ONLY public.venta_detalle_servicio ADD CONSTRAINT fkte4hlh8fw70od2djc68oabyi2 FOREIGN KEY (id_venta) REFERENCES public.venta(id_venta);
